name = "KurSync"
client_id = "47e4ecbf209e9c6a94ad305ea043816c"
application_url = "https://shopify-currency-app-production.up.railway.app"
embedded = true

[access_scopes]
scopes = "write_products,read_products,read_inventory"

[auth]
redirect_urls = [
  "https://shopify-currency-app-production.up.railway.app/auth/callback"
]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks/customers/data_request"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks/customers/redact"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks/shop/redact"

[[webhooks.subscriptions]]
topics = ["products/create"]
uri = "/webhooks/products/create"

[app_proxy]
url = "https://shopify-currency-app-production.up.railway.app"
subpath = "apps"
prefix = "apps"

[pos]
embedded = false